
*************************************************
*** Auxiliary Program: Create Variable Labels ***
*************************************************

capture label var lwage1 "Log Wages"
capture label var covered "Union Covered"
capture label var nonwhite "Non-White"
capture label var nmarr "Non-Married"
capture label var age "Age"
capture label var ed0 "Primary"
capture label var ed1 "Some HS"
capture label var ed2 "High School"
capture label var ed3 "Some College"
capture label var ed4 "College"
capture label var ed5 "Post-Grad"
capture label var ex1 "Exper < 5 yrs"
capture label var ex2 "Exper 5-10 yrs"
capture label var ex3 "Exper 10-15 yrs"
capture label var ex4 "Exper 15-20 yrs"
capture label var ex5 "Exper 20-25 yrs"
capture label var ex6 "Exper 25-30 yrs"
capture label var ex7 "Exper 30-35 yrs"
capture label var ex8 "Exper 35-40 yrs"
capture label var ex9 "Exper >= 40 yrs"
capture label var occd11 "Upper Management"
capture label var occd12 "Lower Management"
capture label var occd21 "Engineers & Computer Occ."
capture label var occd22 "Other Scientists"
capture label var occd23 "Social Support Occ."
capture label var occd24 "Lawyers & Doctors"
capture label var occd25 "Health Treatment Occ."
capture label var occd30 "Clerical Occ."
capture label var occd40 "Sales Occ."
capture label var occd41 "Insur. & Real Estate Sales"
capture label var occd42 "Financial Sales"
capture label var occd50 "Service Occ."
capture label var occd60 "Primary Occ."
capture label var occd70 "Construction & Repair Occ."
capture label var occd80 "Production Occ."
capture label var occd90 "Transportation Occ."
capture label var occd91 "Truckers"
capture label var indd1 "Agriculture & Mining"
capture label var indd2 "Construction"
capture label var indd3 "Hi-Tech Manufac"
capture label var indd4 "Low-Tech Manufac"
capture label var indd5 "Wholesale Trade"
capture label var indd6 "Retail Trade"
capture label var indd7 "Transportation & Utilities"
capture label var indd8 "Information except Hi-Tech"
capture label var indd9 "Financial Activities"
capture label var indd10 "Hi-Tech Services"
capture label var indd11 "Business Services"
capture label var indd12 "Education & Health Services"
capture label var indd13 "Personal Services"
capture label var indd14 "Public Admin"
capture label var pub "Public Sector"
capture label var base "Base group"
